name: healthcheck

on:
  schedule:
    - cron: '0 3 * * *'  # Run at 3:00 AM UTC every day

jobs:
  ampleforth:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: forge build
        id: build

      - name: Run chaincheck test suite
        run: forge test --match-contract "AmpleforthChaincheck"
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        id: ampleforth

  forth-dao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: forge build
        id: build

      - name: Run chaincheck test suite
        run: forge test --match-contract "ForthDAOChaincheck"
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        id: forth-dao

  spot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: forge build
        id: build

      - name: Run chaincheck test suite
        run: forge test --match-contract "SPOTChaincheck"
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        id: spot
