name: invariants

on:
  schedule:
    - cron: '0 6 * * *' # Run at 6:00 AM UTC every day

jobs:
  ampleforth:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: forge build
        id: build

      - name: Run invariants test suite
        run: forge test --match-contract "AmpleforthInvariants"
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        id: ampleforth

  forth-dao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: forge build
        id: build

      - name: Run invariants test suite
        run: forge test --match-contract "ForthDAOInvariants"
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        id: forth-dao

  spot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: forge build
        id: build

      - name: Run invariants test suite
        run: forge test --match-contract "SPOTInvariants"
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        id: spot
